version: '3.8'
services:
  java-app:
    build: .
    ports:
      - "80:80"
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m

  # Prometheus
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - java-app

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring
networks:
  monitoring:
    driver: bridge