server:
    port: 80

management:
    server:
        port: 80
    endpoints:
        web:
            exposure:
                include: health, info, prometheus, metrics
    endpoint:
        prometheus:
            enabled: true
        health:
            enabled: true
        metrics:
            enabled: true
    metrics:
        export:
            prometheus:
                enabled: true

